# Generated by Django 4.2.5 on 2023-09-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mnf_year', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=200)),
                ('rided_km', models.IntegerField()),
                ('gear', models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=500)),
                ('seat', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('posting_date', models.DateField()),
                ('discription', models.CharField(max_length=1000)),
            ],
        ),
    ]
