# Generated by Django 4.2.5 on 2023-09-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olx',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='olx',
            name='gear',
            field=models.CharField(choices=[('automatic', 'automatic'), ('manual', 'manual')], default='manual', max_length=500),
        ),
        migrations.AlterField(
            model_name='olx',
            name='posting_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
