# Generated by Django 4.2.5 on 2023-09-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0002_olx_phone_alter_olx_gear_alter_olx_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olx',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'petrol'), ('Desel', 'desel'), ('CNG', 'cng')], default='Please select one', max_length=200),
        ),
        migrations.AlterField(
            model_name='olx',
            name='gear',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=500),
        ),
    ]
