# Generated by Django 4.2.5 on 2023-09-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0005_alter_olx_fuel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='olx',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='olx',
            name='gear',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=500),
        ),
    ]
