# Generated by Django 4.2.5 on 2023-09-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0006_olx_price_alter_olx_gear'),
    ]

    operations = [
        migrations.AddField(
            model_name='olx',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='olx',
            name='fuel_type',
            field=models.CharField(choices=[('desel', 'Desel'), ('cng', 'CNG'), ('petrol', 'Petrol')], default='petrol', max_length=200),
        ),
    ]
