# Generated by Django 4.2.5 on 2023-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0008_alter_olx_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olx',
            name='fuel_type',
            field=models.CharField(choices=[('cng', 'CNG'), ('petrol', 'Petrol'), ('desel', 'Desel')], default='petrol', max_length=200),
        ),
        migrations.AlterField(
            model_name='olx',
            name='gear',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=500),
        ),
    ]
