# Generated by Django 4.2.5 on 2023-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olx', '0011_alter_olx_fuel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olx',
            name='fuel_type',
            field=models.CharField(choices=[('cng', 'CNG'), ('desel', 'Desel'), ('petrol', 'Petrol')], default='petrol', max_length=200),
        ),
    ]
