# Generated by Django 4.2.5 on 2023-10-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vechiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mnf_year', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('cng', 'CNG'), ('desel', 'Desel'), ('petrol', 'Petrol')], default='petrol', max_length=200)),
                ('rided_km', models.IntegerField()),
                ('gear', models.CharField(choices=[('manual', 'Manual'), ('no_gear', 'No Gear'), ('automatic', 'Automatic')], default='manual', max_length=500)),
                ('seat', models.IntegerField()),
                ('price', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=500)),
                ('posting_date', models.DateField(auto_now_add=True, null=True)),
                ('discription', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
