# Generated by Django 4.2.5 on 2023-10-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiles',
            name='fuel_type',
            field=models.CharField(choices=[('cng', 'CNG'), ('petrol', 'Petrol'), ('desel', 'Desel')], default='petrol', max_length=200),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='gear',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('no_gear', 'No Gear'), ('manual', 'Manual')], default='manual', max_length=500),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='image',
            field=models.ImageField(null=True, upload_to='vechiles/images'),
        ),
    ]
