# Generated by Django 4.2.5 on 2023-10-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0002_alter_vechiles_fuel_type_alter_vechiles_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiles',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('cng', 'CNG'), ('desel', 'Desel')], default='petrol', max_length=200),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='gear',
            field=models.CharField(choices=[('no_gear', 'No Gear'), ('automatic', 'Automatic'), ('manual', 'Manual')], default='manual', max_length=500),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
