# Generated by Django 4.2.5 on 2023-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0004_alter_vechiles_fuel_type_alter_vechiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiles',
            name='fuel_type',
            field=models.CharField(choices=[('cng', 'CNG'), ('desel', 'Desel'), ('petrol', 'Petrol')], default='petrol', max_length=200),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='gear',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('no_gear', 'No Gear')], default='manual', max_length=500),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
