# Generated by Django 4.2.5 on 2023-10-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechiles', '0005_alter_vechiles_fuel_type_alter_vechiles_gear_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vechiles',
            name='gear',
            field=models.CharField(choices=[('manual', 'Manual'), ('no_gear', 'No Gear'), ('automatic', 'Automatic')], default='manual', max_length=500),
        ),
        migrations.AlterField(
            model_name='vechiles',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
